[package]
name = "anchor-metaplex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.21.0"
anchor-spl = "0.21.0"
mpl-token-metadata = { version = "1.2.4", features = ["no-entrypoint"] }
